# terraform-docs Configuration File
#
# This file (.terraform-docs.yml) is used by default by terraform-docs. It is
# used to generate the README for this Terraform module.
#
# To generate documentation, execute the following:
#
#   ```
#   terraform-docs .
#   ```
#
# See the terraform-docs documentation for more information:
#   https://github.com/terraform-docs/terraform-docs/tree/master/docs

formatter: markdown

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: .

sections:
  hide-all: false
  hide: [requirements, providers, modules]
  show-all: true
  show: []

output:
  file: "README.md"
  mode: replace
  template: |-
    # AWS EKS Terraform Module

    [![MIT License](https://img.shields.io/badge/License-MIT-blue.svg)](https://github.com/infrable-io/terraform-aws-eks/blob/master/LICENSE)
    [![Maintained by Infrable](https://img.shields.io/badge/Maintained%20by-Infrable-000000)](https://infrable.io)

    A Terraform module for configuring [Amazon Elastic Kubernetes Service (EKS)](https://aws.amazon.com/eks).

    >Amazon EKS is a managed service that makes it easy for you to use Kubernetes on AWS without needing to install and operate your own Kubernetes control plane.

    ## Overview

    This Terraform module provides an opinionated deployment of Amazon EKS. It comprises the following:
    * Managed Kubernetes control plane via Amazon EKS
    * Compute via managed node groups for running Kubernetes workloads
    * Amazon VPC and subnets with public and private subnets (recommended)
    * Authentication via AWS IAM
    * Authorization via native Kubernetes Role Based Access Control (RBAC)
    * AWS Application Load Balancer (ALB) for Kubernetes Ingress

    ## Terraform Module Documentation

    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
