name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3
      - name: 'Check formatting'
        run: terraform fmt -check -recursive
      - name: 'Validate configuration'
        run: terraform validate
      - name: 'Set up TFLint'
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.56.0
      - name: 'Run TFLint'
        run: tflint -recursive
  security-scan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - name: 'Run Checkov'
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: github_failed_only
